//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumWare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprint()
        {
            this.Taches = new HashSet<Tache>();
            this.UserStorys = new HashSet<UserStory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime CreationDate { get; set; }
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string State { get; set; }
        public string Decision { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime BeginDate { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime EndDate { get; set; }
        public Nullable<int> Cout { get; set; }
        public Nullable<int> Backlog_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual Backlog Backlog { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tache> Taches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStory> UserStorys { get; set; }
    }
}
